<?php

namespace Magenest\Movie\Model\ResourceModel;

use Magento\Framework\Model\AbstractModel;
use Magento\Framework\Model\ResourceModel\Db\AbstractDb;

class Actor extends AbstractDb
{

    public function save(AbstractModel $object)
    {
        return parent::save($object); // TODO: Change the autogenerated stub
    }

    protected function _construct()
    {
        $this->_init('magenest_actor', 'actor_id');
    }

}
