<?php


namespace Magenest\Movie\Model\ResourceModel;


use Magento\Framework\Event\ManagerInterface;
use Magento\Framework\Model\ResourceModel\Db\AbstractDb;

class Movie extends AbstractDb
{
    protected $_eventManager;
    public function __construct(
        \Magento\Framework\Model\ResourceModel\Db\Context $context,
        $connectionName = null,
        ManagerInterface $eventManager
    )
    {
        $this->_eventManager = $eventManager;
        parent::__construct($context, $connectionName);
    }

    protected function _construct()
    {
        $this->_init('magenest_movie', 'movie_id');
    }
    protected function _afterSave(\Magento\Framework\Model\AbstractModel $object)
    {
        $id = ['id' => $object->getId()];
        $this->_eventManager->dispatch('movie_after_save', $id);
        return parent::_afterSave($object); // TODO: Change the autogenerated stub
    }
}
