<div class="block">
	<div class="block-title">
		<strong>My Dashboard</strong>
	</div>
	<div class="block-content">
        <?php
        $customer = $block->getDetailsCurCustomer();
        echo '<div class="box">';
        echo '<img src="'.$this->getUrl('pub/media/customer').$customer['avatar'].'" alt="Avatar" width="100" height="100"> <br></div>';
        echo '<div class="box"><strong>Name: </strong>'.$customer['name'];
        echo '<br><strong>Email: </strong>'.$customer['email'].'</div>';
        ?>
	</div>
</div>

