<div class="fieldset-wrapper customer-information">
	<div class="fieldset-wrapper-title">
		<span class="title"><?= $block->escapeHtml(__('Report module')) ?></span>
	</div>
	<table class="admin__table-secondary">
		<tbody>
		<tr>
			<th>Number of module installed</th>
			<td><?php echo $block->getNumberOfInstalledModule() ?></td>
		</tr>
		<tr>
			<th>Number of another module installed</th>
			<td><?php echo $block->getNumOfExternalModule() ?></td>
		</tr>
		</tbody>
	</table>
	<table class="admin__table-secondary">
		<tbody>
		<tr>
			<th>Number of module installed</th>
			<td><?php echo $block->getNumberOfInstalledModule() ?></td>
		</tr>
		<tr>
			<th>Number of another module installed</th>
			<td><?php echo $block->getNumOfExternalModule() ?></td>
		</tr>
		</tbody>
	</table>

</div>
<!--<div class="admin__page-section-title">-->
<!--	<span class="title">Report module</span>-->
<!--</div>-->
<!--<div class="admin__page-section-content">-->
<!--	<div class="admin__page-section-item">-->
<!--		<div class="admin__page-section-item-title">-->
<!--			<span class="title">Total modules </span>-->
<!--		</div>-->
<!--	</div>-->
<!--	<div class="admin__page-section-item-content">-->
<!--		<table class="admin__table-secondary">-->
<!--			<tbody>-->
<!--			<tr>-->
<!--				<th>Number of module installed</th>-->
<!--				<td>--><?php //echo $block->getNumberOfInstalledModule() ?><!--</td>-->
<!--			</tr>-->
<!--			<tr>-->
<!--				<th>Number of another module installed</th>-->
<!--				<td>--><?php //echo $block->getNumOfExternalModule() ?><!--</td>-->
<!--			</tr>-->
<!--			</tbody>-->
<!--		</table>-->
<!--	</div>-->
<!---->
<!--	<div class="admin__page-section-item">-->
<!--		<div class="admin__page-section-item-title">-->
<!--			<span class="title">Total modules </span>-->
<!--		</div>-->
<!--	</div>-->
<!--	<div class="admin__page-section-item-content">-->
<!--		<table class="admin__table-secondary">-->
<!--			<tbody>-->
<!--			<tr>-->
<!--				<th>Number of module installed</th>-->
<!--				<td>--><?php //echo $block->getNumberOfInstalledModule() ?><!--</td>-->
<!--			</tr>-->
<!--			<tr>-->
<!--				<th>Number of another module installed</th>-->
<!--				<td>--><?php //echo $block->getNumOfExternalModule() ?><!--</td>-->
<!--			</tr>-->
<!--			</tbody>-->
<!--		</table>-->
<!--	</div>-->
<!--</div>-->
<!---->
